### ISSUE TITLE
"Undefined index: frontendUrl" error when adding a new product

### ISSUE THREAD

**Issue by maxvergelli** [thecodeholic/yii2-ecommerce-website#5]
I get this error when I add a new product (with or without the image):

Undefined index: frontendUrl

    1. in C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\common\models\Product.php at line 174
 

            return self::formatImageUrl($this->image);
        }
     
        public static function formatImageUrl($imagePath)
        {
            if ($imagePath) {
                **return Yii::$app->params['frontendUrl'] . '/storage' . $imagePath;**
            }
     
            **return Yii::$app->params['frontendUrl'] . '/img/no_image_available.png';**  
        }
     
        /**
         * Get short version of the description
         *
         * @return string
         * @author Zura Sekhniashvili <zurasekhniashvili@gmail.com>
         */
        public function getShortDescription()

yii\base\ErrorException: Undefined index: frontendUrl in C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\common\models\Product.php:174
Stack trace:
#0 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\common\models\Product.php(174): yii\base\ErrorHandler->handleError()
#1 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\common\models\Product.php(165): common\models\Product::formatImageUrl()
#2 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\backend\views\product\view.php(36): common\models\Product->getImageUrl()
#3 [internal function]: yii\base\View->{closure}()
#4 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\widgets\DetailView.php(245): call_user_func()
#5 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\widgets\DetailView.php(143): yii\widgets\DetailView->normalizeAttributes()
#6 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\base\BaseObject.php(109): yii\widgets\DetailView->init()
#7 [internal function]: yii\base\BaseObject->__construct()
#8 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\di\Container.php(418): ReflectionClass->newInstanceArgs()
#9 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\di\Container.php(169): yii\di\Container->build()
#10 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\BaseYii.php(365): yii\di\Container->get()
#11 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\base\Widget.php(138): yii\BaseYii::createObject()
#12 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\backend\views\product\view.php(56): yii\base\Widget::widget()
#13 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\base\View.php(348): require('C:\\Users\\Max\\De...')
#14 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\base\View.php(257): yii\base\View->renderPhpFile()
#15 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\base\View.php(156): yii\base\View->renderFile()
#16 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\base\Controller.php(409): yii\base\View->render()
#17 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\backend\controllers\ProductController.php(68): yii\base\Controller->render()
#18 [internal function]: backend\controllers\ProductController->actionView()
#19 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array()
#20 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\base\Controller.php(180): yii\base\InlineAction->runWithParams()
#21 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction()
#22 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\web\Application.php(104): yii\base\Module->runAction()
#23 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\vendor\yiisoft\yii2\base\Application.php(392): yii\web\Application->handleRequest()
#24 C:\Users\Max\Desktop\Archivio\Websites\WAMP\frameworks\yii2\webroot\backend\web\index.php(17): yii\base\Application->run()
#25 {main}

**Comment by maxvergelli** [comment]
After product's data saved in the database, the error is shown at "http://backend.localhost/product/view?id=3"

**Comment by thecodeholic** [comment]
I think you have not edited `common/config/params-local.php` file. 
Please check the 8th point from [Installation section](https://github.com/thecodeholic/yii2-ecommerce-website#installation) of the readme.
You should add `frontendUrl` there.

**Comment by maxvergelli** [comment]
You are right! I forgot the parameters, I thought it was generic settings only for paypal
