### ISSUE TITLE
theming frontend

### ISSUE THREAD

**Issue by paskuale75** [thecodeholic/yii2-ecommerce-website#8]
Is it possible to customize the frontend layout with a theme ?
Thanks

**Comment by ajpgtech** [comment]
@paskuale75 , this is not an 'issue' as such and I would recommend closing it.

It is certainly possible to create an alternate theme. Have a look at the Yii docs regarding this
https://www.yiiframework.com/doc/guide/2.0/en/output-theming

Perhaps an alternate issue can be raised, or your issue can be reworded as a feature request to support themes.
